name: $(Build.SourceBranch)$(Rev:.r)

trigger:
  - master

phases:
  - phase: Test
    queue: Hosted Ubuntu 1604
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6 >= 3.5'
        addToPath: true
        architecture: 'x64'

    - script: |
        pip install --upgrade pip==18.0
        pip --version
      condition: succeeded()
      displayName: upgrade pip

    - script: |
        pip --version
        pip install -r requirements.txt
        pip install -e .
      condition: succeeded()
      displayName: install aztk

    - script: |
        yapf --style .style.yapf -dpr aztk/ aztk_cli/
      condition: succeeded()
      displayName: yapf

    - script: |
        pylint --jobs 2 --errors-only aztk aztk_cli
      condition: succeeded()
      displayName: pylint error check

    - script: |
        pytest --ignore=tests/integration_tests
      condition: succeeded()
      displayName: unit tests

    - script: |
        pytest --numprocesses=75 tests/integration_tests
      condition: and(succeeded(), or(startsWith(variables['Build.SourceBranchName'], 'release'), eq(variables['Build.SourceBranchName'], 'master')))
      displayName: integration tests

    - script: |
        pylint --jobs 2 --disable=fixme aztk aztk_cli
      continueOnError: true
      condition: succeeded()
      displayName: pylint report
