trigger:
  - master


phases:
- phase: Test
  queue: Hosted Ubuntu 1604
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '>= 3.5' 
      addToPath: true 
      architecture: 'x64'

  - script: |
      pip install -r requirements.txt
      pip install -e .
    condition: succeeded()
    displayName: install aztk

  - script: |
      yapf -dr aztk/ aztk_cli/
    condition: succeeded()
    displayName: yapf

  - script: |
      pytest -n 50
    condition: succeeded()
    displayName: pytest
