name: release aztk

on:
  push:
    branches:
      - master
    paths:
      - aztk_version

env:
  ACR_DOCKER_REPO: ${{ secrets.ACR_DOCKER_REPO }}
  ACR_DOCKER_USERNAME: ${{ secrets.ACR_DOCKER_USERNAME }}
  ACR_DOCKER_PASSWORD: ${{ secrets.ACR_DOCKER_PASSWORD }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get versioning information
        id: versionings
        run: |
          echo "::set-output name=AZTK_VER::$(tail -n 1 aztk_version)"

      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          SLACK_CHANNEL: release
          SLACK_COLOR: '#3278BD'
          SLACK_TITLE: Release Aztk
          SLACK_USERNAME: Github Action
          SLACK_MSG_AUTHOR: $GITHUB_ACTOR

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.versionings.outputs.AZTK_VER }}
          release_name: ${{ steps.versionings.outputs.AZTK_VER }}
          body_path: aztk_version
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
