name: release aztk

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag: Aztk Version'
        required: true

env:
  ACR_DOCKER_REPO: ${{ secrets.ACR_DOCKER_REPO }}
  ACR_DOCKER_USERNAME: ${{ secrets.ACR_DOCKER_USERNAME }}
  ACR_DOCKER_PASSWORD: ${{ secrets.ACR_DOCKER_PASSWORD }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.tags }}
          release_name: ${{ github.event.inputs.tags }}
          body_path: aztk_version
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: release
          SLACK_COLOR: '#3278BD'
          SLACK_TITLE: Release-Aztk-${{ github.event.inputs.tags }}
          SLACK_USERNAME: Github Action
          SLACK_MSG_AUTHOR: $GITHUB_ACTOR
